### ISSUE TITLE
Bad input file

### ISSUE THREAD

**Issue by hyanwong** [SajadMirzaei/RentPlus#3]
the following input file seems to crash RentPlus:

```
362 473 560 603 605 1086 1215 1362 1369 1391 1470 1546 1694 1718
11010000100001
00000010011010
11010000100001
11010000100001
11000100000000
11010000100001
11100100000000
11010000100001
11010001100001
11001000000100
```

As far as I can see, this is a reasonable input file, but I get

```
java -jar RentPlus/RentPlus.jar ../bad.dat 
Start Time: Tue Feb 07 22:00:08 GMT 2017
Reading Hap Matrix from input file
Initiating TMRCAs
Reading positions
Making Distance Matrices [0.0010 Seconds] 
Making Guide TreesException in thread "main" java.util.NoSuchElementException
	at java.util.TreeMap.key(TreeMap.java:1206)
	at java.util.TreeMap.firstKey(TreeMap.java:267)
	at java.util.TreeSet.first(TreeSet.java:377)
	at main.Main.makeGuideTrees(Main.java:486)
	at main.Main.<init>(Main.java:139)
	at main.Main.main(Main.java:2316)
```

**Comment by SajadMirzaei** [comment]
It is fixed. Thank you.
