### ISSUE TITLE
Occasional error "ArrayIndexOutOfBoundsException"

### ISSUE THREAD

**Issue by hyanwong** [SajadMirzaei/RentPlus#5]
Like this:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -32768
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at main.Main.findCompatibleRegion(Main.java:660)
	at main.Main.makeGuideTrees(Main.java:466)
	at main.Main.<init>(Main.java:142)
	at main.Main.main(Main.java:2321)
Command exited with non-zero status 1

post here if you need me to provide an input file.

**Comment by SajadMirzaei** [comment]
I appreciate it if you send me an input file. You can also email me at mirzaei dot sajad at gmail. Thanks.

**Comment by hyanwong** [comment]
Easy to post here: `java -jar RentPlus.jar crashtest.txt`:

```
Start Time: Tue May 01 09:31:36 BST 2018
Reading Hap Matrix from input file
Initiating TMRCAs
Reading positions
Making Distance Matrices [0.731 Seconds] 
Making Guide TreesException in thread "main" java.lang.ArrayIndexOutOfBoundsException: -32768
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at main.Main.findCompatibleRegion(Main.java:660)
	at main.Main.makeGuideTrees(Main.java:466)
	at main.Main.<init>(Main.java:142)
	at main.Main.main(Main.java:2321)

```

[crashtest.txt](https://github.com/SajadMirzaei/RentPlus/files/1963323/crashtest.txt)
